### PR TITLE
Update to Julia 1.0

### PR DESCRIPTION
**Pull request by tkonolige**
This PR updates PyAMG.jl to be compatible with Julia 1.0. I removed `A_ldiv_B!` and `A_mul_B!` as they have been removed. The PyCall syntax is also changed from `@pyimport` to just `pyimport`. I also added a `Project.toml` for the new package manager.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
>I removed A_ldiv_B! and A_mul_B! as they have been removed. 

They weren't removed, just renamed. `mul!`, `ldiv!`

**Comment by tkonolige** [comment]
My bad, fixed.

**Comment by cortner** [comment]
Looks good to me. Thanks Chris for catching this.

**Comment by cortner** [comment]
I forgot - did I give you push access? Ie can you merge?

**Comment by ChrisRackauckas** [comment]
Nope

**Comment by cortner** [comment]
sorry, I actually mean t @tkonolige  - I recently gave somebody access but it was somebody else. 

@ChrisRackauckas  If you'd like push access I'm happy to give it to you. Do you still use this or have you switched to `AMG.jl`?

**Comment by cortner** [comment]
@tkonolige if you are using `PyAMG.jl` and are planning to keep this running, then I'd be happy to give you push access as well.

Thank you very much in the meantime for upgrading this to 1.0!

**Comment by ChrisRackauckas** [comment]
I haven't used this in awhile, but would be fine helping you maintain it. It seems like a pretty low maintenance library.

**Comment by cortner** [comment]
Correct - I just haven’t moved to 1.0 yet. (Need to complete a large project first)

**Pull request merged**
