### PR TITLE
updates for 0.7

### PR DESCRIPTION
**Pull request by omalled**
This gets the tests working on 0.7 without any deprecation warnings

### CODE REVIEW

**Comment by cortner** [comment]
I'm really no longer maintaining this, since `AlgebraicMultigrid.jl` has become available. If you want this merged, then can I suggest to also fix `REQUIRE` and the travis tests? I can then tag a 0.7 version.  I'm also happy to give you control over this package if you wish.

**Comment by omalled** [comment]
Sorry, I wasn't trying to impose additional maintenance. I'd be willing to take over control of the package, but I'm not sure if I have the requisite skills. E.g., I don't really know how to fix the `REQUIRE` (do I just add `SparseArrays` and `LinearAlgebra` to the list?) or how to work with the travis tests.

`AlgebraicMultigrid.jl` looks great, and having a pure julia AMG is appealing. However, I ran into an [issue](https://github.com/JuliaLinearAlgebra/AlgebraicMultigrid.jl/issues/46) in trying to migrate to that. I think that experience highlights the value of having a more mature AMG library available.

**Comment by cortner** [comment]
I though I just transferred this - but it seems I still own it?

**Comment by cortner** [comment]
as an alternative I also added you as a collaborator. Maybe that could actually be an easier temporary solution - since the registration of the package would probably be affected? If this is becoming an issue, could you open a formal issue about it where we can fix the transfer?

**Pull request merged**
